# file: .github/workflows/hello-world.yml
name: hello-world
# on – определяет события, которые запускают workflow
on: push
jobs:
 # build – произвольно выбранное имя задания
 # их может быть больше одного
 build:
 # операционная система для работы workflow
 runs-on: ubuntu-latest
 steps: # список шагов, которые надо выполнить
 # actions — выполняет какую-то задачу
 # checkout — клонирует репозиторий
 - uses: actions/checkout@v2
 # run – произвольная bash-команда
 # ls -la выведет содержимое текущего репозитория
 - run: ls -la
